# -*- coding: utf-8 -*-
"""Tarea_Clase10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H8JpJYEecHbCvC8CVgUJZyWC9A736ono
"""

import math

#Valor de G en el S.I.
G = 6.674e-11

#Solicitud de masa (M)
M = float(input("ingrese el valor de la masa en kg: "))

#Solicitud de radio (R)
R = float(input("ingrese el valor de radio en metros: "))

#Operacion para calcular la velocidad de escape (Ve)
Ve = math.sqrt((2*G*M)/R)

#Mostrar el resultado en m/s
print(f"Ve = {Ve:.2f} este es el resultado en m/s")

#Conversion de m/s a km/s
print(f"Ve = {Ve/1000:.2f} este es el resultado en km/s")

