# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12gIojzLiwt4wGFBA077Mr0XUvnmIGTee
"""

import math
"""Números pares e inpares"""
n = int(input("Ingrese un numero:  "))
if n % 2 == 0:
  print("El numero es par")
else:
  print("El numero es impar")