# -*- coding: utf-8 -*-
"""tarea_algebraL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zRwLMoCXNDvi5lpuOPTADh7M--Pf5MSm
"""

import numpy as np

j = np.array ([[1/5., 1, 1, 1, -1, -1], [1, 0, 1, -1, 5, 1],[-1, -3, 2, -1, -1, -1], [0, 5, -1, 1, 2, 0], [1, -2, 3, 1/2., 0, 0],[1/2, -2, -2, -1, 1, -6]], dtype=float)
a = np.array ([24.1312, 46.2798, -61.8372, 31.1466, 51.2106, -5.7008], dtype=float)

sol=np.linalg.solve(j,a)
autovalores, autovectores = np.linalg.eig(j)
det= np.linalg.det(j)

print(f"la solucion de la matriz j es {sol}\n")
print(f"los autovalores de la matriz j son {autovalores}\n")
print(f"los autovectores de la matriz j son {autovectores}\n")
print(f"el determinante de la matriz j es {det}\n")

