# -*- coding: utf-8 -*-
"""tarea_de_algebra_lineal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dTPMKv_0etscIvxIsAlwRDU3mLlAUKg8
"""

import numpy as np

A = np.array([[1/5.,1,1,1,-1,-1] , [1,0,1,-1,5,1] , [-1,-3,2,-1,-1,-1] , [0,5,-1,1,2,0] , [1,-2,3,1/2.,0,0] , [1/2.,-2,-2,-1,1,-6]], dtype=float)
C = np.array([24.1312,46.2798,-61.8372,31.1466,51.2106,-5.7008], dtype=float)
print(A)
print(C)

det= np.linalg.det(A)
autovalores , autovectores = np.linalg.eig(A)
sln= np.linalg.solve(A,C)

print(f"los autovalores son:{autovalores}")
print(f"el determinante es:{det}")
print(f"la solucion es:{sln}")